//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AirCavLOS.rc
//
#define IDOK2                           3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_AIRCAVLOS_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_UNKNOWN_HEX          129
#define IDD_DIALOG_ELEV_OFFSET          130
#define IDB_BITMAP1                     134
#define IDD_DIALOG_SCENARIO             137
#define IDD_DIALOG_OPPFIRE              139
#define IDD_DIALOG_KILL                 140
#define IDD_DIALOG_UNIT_DETAILS         141
#define IDD_DIALOG_KILL2                141
#define IDD_DIALOG_INDIRECT_FIRE        145
#define IDD_DIALOG_KILL_SUP             146
#define IDC_LIST_UNITS                  1000
#define IDC_BUTTON_ACTION_PASS          1001
#define IDC_BUTTON_ACTION_FIRE          1002
#define IDC_BUTTON_ACTION_MOVE_N        1003
#define IDC_BUTTON_ACTION_MOVE_NW       1004
#define IDC_BUTTON_ACTION_MOVE_SW       1005
#define IDC_BUTTON_ACTION_MOVE_S        1006
#define IDC_BUTTON_ACTION_MOVE_SE       1007
#define IDC_BUTTON_ACTION_MOVE_NE       1008
#define IDC_LIST_SIGHTED_UNITS          1009
#define IDC_EDIT_ACTIVE_NAME            1010
#define IDC_EDIT_CUR_TURN               1011
#define IDC_BUTTON_ACTION_EVADE         1012
#define IDC_BUTTON_ACTION_RESET         1013
#define IDC_LIST_SIGHTING_UNITS         1014
#define IDC_BUTTON_ACTION_DEFILADE      1015
#define IDC_RADIO_ACTIVE_MAIN1          1016
#define IDC_RADIO_ACTIVE_SECONDARY1     1017
#define IDC_EDIT_ACTIVE_OP              1018
#define IDC_RADIO_ACTIVE_SECONDARY2     1019
#define IDC_BUTTON_MAKE_ACTIVE          1020
#define IDC_EDIT_ACTIVE_SIDE            1021
#define IDC_EDIT_ACTIVE_LOC             1022
#define IDC_EDIT_ACTIVE_OFFSET          1023
#define IDC_EDIT_ACTIVE_UNIT_TYPE       1024
#define IDC_EDIT_ACTIVE_TARGET_TYPE     1025
#define IDC_EDIT_ACTIVE_MAIN_WPN1       1026
#define IDC_EDIT_ACTIVE_SECONDARY_WPN1  1027
#define IDC_EDIT_ACTIVE_UNIT_TYPE_NAME  1028
#define IDC_EDIT_ACTIVE_UNIT_COUNTRY    1029
#define IDC_TERRAIN_CLEAR               1030
#define IDC_EDIT_TERR_TER               1030
#define IDC_EDIT_ACTIVE_STATUS          1030
#define IDC_TERRAIN_WOODS               1031
#define IDC_EDIT_TERR_ELEV              1031
#define IDC_TERRAIN_TOWN                1032
#define IDC_EDIT_ACTIVE_ACTUALELEV      1032
#define IDC_TERRAIN_RIVER               1033
#define IDC_RADIO_ACTIVE_MAIN2          1033
#define IDC_ELEVATION                   1034
#define IDC_RADIO_ACTIVE_MAIN3          1034
#define IDC_CHECK_ROAD                  1035
#define IDC_EDIT_ACTIVE_MAIN_WPN2       1035
#define IDC_CHECK_CONTOUR               1036
#define IDC_EDIT_ACTIVE_MAIN_WPN3       1036
#define IDC_RADIO_ELEV_0                1037
#define IDC_EDIT_ACTIVE_SECONDARY_WPN2  1037
#define IDC_RADIO_ELEV_10               1038
#define IDC_BUTTON_ACTION_MOUNT         1038
#define IDC_RADIO_ELEV_20               1039
#define IDC_BUTTON_ACTION_LOWLEVEL      1039
#define IDC_RADIO_ELEV_30               1040
#define IDC_BUTTON_RESET_ACTIVE         1040
#define IDC_RADIO_ELEV_40               1041
#define IDC_BUTTON_ACTION_OPPFIRE       1041
#define IDC_RADIO_ELEV_50               1042
#define IDC_LIST_FIRING_UNITS           1042
#define IDC_RADIO_ELEV_60               1043
#define IDC_BUTTON_RESET_FIRING         1043
#define IDC_RADIO_ELEV_70               1044
#define IDC_BUTTON_RESOLVE_OPPFIRE      1044
#define IDC_RADIO_ELEV_80               1045
#define IDC_BUTTON_LIST_ALL             1045
#define IDC_CHECK_AUTOBAHN              1046
#define IDC_BUTTON_ACTION_INDFIRE       1046
#define IDC_CHECK_R_N                   1047
#define IDC_CHECK_R_NW                  1048
#define IDC_CHECK_CONTOUR_LINES         1048
#define IDC_CHECK_R_SW                  1049
#define IDC_CHECK_R_NW3                 1049
#define IDC_CHECK_R_S                   1050
#define IDC_CHECK_R_SW3                 1050
#define IDC_CHECK_R_SE                  1051
#define IDC_CHECK_R_S3                  1051
#define IDC_CHECK_R_NE                  1052
#define IDC_CHECK_R_SE3                 1052
#define IDC_CHECK_R_NE3                 1053
#define IDC_CHECK_A_N                   1053
#define IDC_CHECK_R_N3                  1054
#define IDC_CHECK_A_NW                  1054
#define IDC_CHECK_R_NW4                 1055
#define IDC_CHECK_A_SW                  1055
#define IDC_CHECK_R_SW4                 1056
#define IDC_CHECK_A_S                   1056
#define IDC_CHECK_R_S4                  1057
#define IDC_CHECK_A_SE                  1057
#define IDC_CHECK_R_SE4                 1058
#define IDC_CHECK_A_NE                  1058
#define IDC_CHECK_R_NE4                 1059
#define IDC_CHECK_RIVER                 1059
#define IDC_BUTTON_EDIT_TERRAIN         1060
#define IDC_CHECK_R_N4                  1061
#define IDC_CHECK_V_N                   1061
#define IDC_CHECK_R_NW5                 1062
#define IDC_CHECK_V_NW                  1062
#define IDC_CHECK_R_SW5                 1063
#define IDC_CHECK_V_SW                  1063
#define IDC_CHECK_R_S5                  1064
#define IDC_CHECK_V_S                   1064
#define IDC_CHECK_R_SE5                 1065
#define IDC_CHECK_V_SE                  1065
#define IDC_CHECK_R_NE5                 1066
#define IDC_CHECK_V_NE                  1066
#define IDC_SPIN1                       1067
#define IDC_CHECK_ACTIVE_FIRED          1068
#define IDC_CHECK_ACTIVE_MOVED          1069
#define IDC_CHECK_DEBUG                 1070
#define IDC_CHECK_DEBUG_PK              1071
#define IDC_RADIO_SCENARIO_0            1071
#define IDC_CHECK_ACTIVE_EVADING        1072
#define IDC_RADIO_SCENARIO_1            1072
#define IDC_RADIO_OPP_MAIN1             1072
#define IDC_CHECK_ACTIVE_IN_DEF         1073
#define IDC_RADIO_SCENARIO_2            1073
#define IDC_RADIO_OPP_MAIN2             1073
#define IDC_CHECK_ACTIVE_LOWLEVEL       1074
#define IDC_RADIO_SCENARIO_3            1074
#define IDC_RADIO_OPP_MAIN3             1074
#define IDC_RADIO_SCENARIO_4            1075
#define IDC_RADIO_OPP_SECOND1           1075
#define IDC_BUTTON_REMOVE_SMOKE         1075
#define IDC_RADIO_SCENARIO_5            1076
#define IDC_RADIO_OPP_SECOND2           1076
#define IDC_CHECK_POP_SMOKE             1076
#define IDC_RADIO_SCENARIO_6            1077
#define IDC_EDIT_ACTIVE_TARGET_TYPE2    1077
#define IDC_RADIO_SCENARIO_7            1078
#define IDC_BUTTON_EDIT_TERRAIN2        1078
#define IDC_EDIT_MAINWPN1               1079
#define IDC_RADIO_SCENARIO_8            1079
#define IDC_BUTTON_SAVE_PROGRESS        1079
#define IDC_EDIT_MAINWPN2               1080
#define IDC_EDIT_FKN                    1080
#define IDC_RADIO_SCENARIO_9            1080
#define IDC_EDIT_ACTIVE_SIDE2           1080
#define IDC_EDIT_MAINWPN3               1081
#define IDC_EDIT_FKN2                   1081
#define IDC_RADIO_SCENARIO_10           1081
#define IDC_BUTTON_ABOUT                1081
#define IDC_EDIT_MAINWPN4               1082
#define IDC_BUTTON_LAYSMOKE             1082
#define IDC_RADIO_SCENARIO_11           1082
#define IDC_EDIT_MAINWPN5               1083
#define IDC_CHECK_SMOKE                 1083
#define IDC_BUTTON_ELEVOFFSET           1084
#define IDC_NEXT                        1085
#define IDC_EDIT_TERR_STACK             1085
#define IDC_PREVIOUS                    1086
#define IDC_COMBO_WEATHER               1086
#define IDC_GOTO                        1087
#define IDC_CHECK_WRECK                 1087
#define IDC_COMBO_INDIRECT              1088
#define IDC_CHECK_ACTIVE_SUPPRESSED     1088
#define IDC_CHECK_SMOKE_MISSION         1089
#define IDC_CHECK_IGNORE_WATER          1089
#define IDC_CHECK_IGNORE_AUTOBAHN       1090
#define IDC_BUTTON_ACTION_MOVE_N2       1091
#define IDC_BUTTON_ACTION_MOVE_NE2      1092
#define IDC_BUTTON_ACTION_MOVE_SE2      1093
#define IDC_BUTTON_ACTION_MOVE_S2       1094
#define IDC_BUTTON_ACTION_MOVE_SW2      1095
#define IDC_BUTTON_ACTION_MOVE_NW2      1096
#define IDC_CHECK_ROTATE_MAP            1097
#define IDC_BUTTON_ACTION_PREVIOUS_MOVE 1098
#define IDC_COMBO_TIME_OF_DAY           1099
#define IDC_COMBO_OPTICS                1100
#define IDC_BUTTON_ACTION_LASER         1101
#define IDC_BUTTON_ACTION_RADAR         1102
#define IDC_CHECK_ACTIVE_SUPPRESSED2    1103
#define IDC_CHECK_ACTIVE_RADAR_ON       1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
